# Created at 2022-09-28T12:42:26.833
org.testng.TestNGException: 
Two tests in the same suite cannot have the same name: Test4
	at org.testng.TestNG.checkTestNames(TestNG.java:990)
	at org.testng.TestNG.sanityCheck(TestNG.java:979)
	at org.testng.TestNG.run(TestNG.java:1011)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)


